export const itStudentAchievements = [
  { sno: 1, name: "Geethaarun Priya SB (II/IT)", event: "Idea Quest", level: "National", award: "Second Prize", title: "Idea Quest 2025" },
  { sno: 2, name: "Gopika V (II/IT)", event: "Idea Quest", level: "National", award: "Second Prize", title: "Idea Quest 2025" },
  { sno: 3, name: "Ardhanari L (II/IT)", event: "Idea Quest", level: "National", award: "First Prize", title: "Idea Quest 2025" },
  { sno: 4, name: "Lakasana S (II/IT)", event: "Idea Quest", level: "National", award: "First Prize", title: "Idea Quest 2025" },
  { sno: 5, name: "Kalkki R (II/IT)", event: "Idea Quest", level: "National", award: "Second Prize", title: "Idea Quest 2025" },
  { sno: 6, name: "Jeenvan S (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 7, name: "Dhanush Kumar S (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 8, name: "Balaji SR (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 9, name: "Dhanush Kumar S (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Conclave 2025" },
  { sno: 10, name: "Jeevan S (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 11, name: "Balaji SR (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 12, name: "Boopathi Raja P (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 13, name: "Srina S (II/IT)", event: "Code Debugging", level: "National", award: "Second Prize", title: "Code Debugger 2026" },
  { sno: 14, name: "Rashmi NS (II/IT)", event: "Thinkathon", level: "National", award: "Second Prize", title: "Thinkathon 2026" },
  { sno: 15, name: "Rashmi NS (II/IT)", event: "Code Debugging", level: "National", award: "Third Prize", title: "Code Debugger 2026" },
  { sno: 16, name: "Srina S (II/IT)", event: "Thinkathon", level: "National", award: "First Prize", title: "Thinkathon (2025–2026)" },
  { sno: 17, name: "Mohammed Thaleeb (II/IT)", event: "Code Debugging", level: "National", award: "First Prize", title: "Code Debugger 2026" },
  { sno: 18, name: "Mohammed Thaleeb (II/IT)", event: "Thinkathon", level: "National", award: "First Prize", title: "Thinkathon (2025–2026)" },
  { sno: 19, name: "Saranya SD (II/IT)", event: "Code Debugging", level: "National", award: "First Prize", title: "Code Debugger 2026" },
  { sno: 20, name: "Saranya SD (II/IT)", event: "Thinkathon", level: "National", award: "First Prize", title: "Thinkathon (2025–2026)" },
  { sno: 21, name: "Gomathi Sankar (II/IT)", event: "Paper Presentation", level: "National", award: "Pre-Finalist", title: "Conclave 2025" },
  { sno: 22, name: "Gomathi Sankar (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Conclave 2026" },
  { sno: 23, name: "SriSakthi V (II/IT)", event: "Code Debugging", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 24, name: "SriSakthi V (II/IT)", event: "Thinkathon", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 25, name: "Naveen K (II/IT)", event: "Code Debugging", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 26, name: "Naveen K (II/IT)", event: "Thinkathon", level: "National", award: "Second Prize", title: "Conclave 2025" },
  { sno: 27, name: "Miruthala V (II/IT)", event: "Code Debugging", level: "National", award: "Second Prize", title: "Code Debugger 2026" },
  { sno: 28, name: "Miruthala V (II/IT)", event: "Thinkathon", level: "National", award: "Third Prize", title: "Thinkathon 2026" },
  { sno: 29, name: "Vedhasri G (II/IT)", event: "Code Debugging", level: "National", award: "First Prize", title: "Code Debugger 2026" },
  { sno: 30, name: "Vedhasri G (II/IT)", event: "Thinkathon", level: "National", award: "First Prize", title: "Thinkathon 2026" },
  { sno: 31, name: "Francisca Mary A (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 32, name: "Logith Prasath RS (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 33, name: "Devaprakash S (II/IT)", event: "Treasure Hunt", level: "National", award: "Second Prize", title: "Treasure Hunt (2025–2026)" },
  { sno: 34, name: "Devaprakash S (II/IT)", event: "Workshop", level: "National", award: "Second Prize", title: "Workshop (2025–2026)" },
  { sno: 35, name: "Dharshini T (II/IT)", event: "Mobility 2.0 Hackathon", level: "National", award: "Second Prize", title: "Mobility 2.0 Hackathon (2025–2026)" },
  { sno: 36, name: "Dharshini T (II/IT)", event: "Paper Presentation", level: "National", award: "Second Prize", title: "Paper Presentation 2026" },
  { sno: 37, name: "Dharshini T (II/IT)", event: "Squid Game", level: "National", award: "Second Prize", title: "Squid Game (2025–2026)" },
  { sno: 38, name: "Dharshini T (II/IT)", event: "Debug Duel", level: "National", award: "Third Prize", title: "Debug Duel (2025–2026)" },
  { sno: 39, name: "Dharshini T (II/IT)", event: "Treasure Hunt", level: "National", award: "First Prize", title: "Treasure Hunt (2025–2026)" },
  { sno: 40, name: "Vikranth V (II/IT)", event: "Proto Expo", level: "National", award: "Second Prize", title: "Proto Expo 2025" },
  { sno: 41, name: "Saravana T (II/IT)", event: "Proto Expo", level: "National", award: "Second Prize", title: "Proto Expo 2025" },
  { sno: 42, name: "Muthykumaran M (II/IT)", event: "Proto Expo", level: "National", award: "Second Prize", title: "Proto Expo 2025" },
  { sno: 43, name: "Vikranth V (II/IT)", event: "Non-Technical Event", level: "National", award: "Third Prize", title: "Non-Technical Event (2025–2026)" },
  { sno: 44, name: "Rakshitha SKS (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 45, name: "Sudheksha S (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 46, name: "Shanmugapriya S (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 47, name: "Vasundhra S (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 48, name: "Manoranjini Y (II/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 49, name: "Vedhasri G (II/IT)", event: "Paper Presentation", level: "National", award: "Pre-Finalist", title: "Paper Presentation 2026" },
  { sno: 50, name: "Deepakkumar A (I/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 51, name: "Dinakar S (I/IT)", event: "Paper Presentation", level: "National", award: "First Prize", title: "Paper Presentation 2026" },
  { sno: 52, name: "Imrankhan M (II/IT)", event: "Quiz Whizzer", level: "National", award: "Pre-Finalist", title: "Quiz Whizzer (2025–2026)" },
  { sno: 53, name: "Priyadharshini D (III/IT)", event: "Youth Talk 2025", level: "National", award: "Pre-Finalist", title: "Youth Talk 2025" }
];
export const itFacultyAchievements = [];
export const itStudentAwards = [
  { sno: 1, name: "Sahul Hameed Dhameem M\n(III Year B.Tech IT)", event: "Gravito Hacks", level: "National", award: "Winner – Cash Award ₹15,000", title: "Hackathon" },
  { sno: 2, name: "Lalithsanjaai S\n(III Year B.Tech IT)", event: "Gravito Hacks", level: "National", award: "Winner – Cash Award ₹15,000", title: "Hackathon" },
  { sno: 3, name: "Kamaraj D\n(III Year B.Tech IT)", event: "Gravito Hacks", level: "National", award: "Winner – Cash Award ₹15,000", title: "Hackathon" },
  { sno: 4, name: "Mathan Kumar N\n(III Year B.Tech IT)", event: "Gravito Hacks", level: "National", award: "Winner – Cash Award ₹15,000", title: "Hackathon" },
  { sno: 5, name: "Balaji S\n(III Year B.Tech IT)", event: "Gravito Hacks", level: "National", award: "Winner – Cash Award ₹15,000", title: "Hackathon" },
  { sno: 6, name: "Pranesh S\n(III Year B.Tech IT)", event: "HACK XELERATE '25", level: "National", award: "Winner – Cash Award ₹3,000", title: "24-Hour National Level Hackathon" },
  { sno: 7, name: "M Sahul Hameed Dhameem\n(III Year B.Tech IT)", event: "HACKXTREME'26", level: "National", award: "Second Prize – Cash Award ₹15,000 & Internship Offer (Greensoft Solutions, Trichy)", title: "24-Hour National Level Hackathon" },
  { sno: 8, name: "A S Somasundharan\n(III Year B.Tech IT)", event: "HACKXTREME'26", level: "National", award: "Second Prize – Cash Award ₹15,000 & Internship Offer (Greensoft Solutions, Trichy)", title: "24-Hour National Level Hackathon" },
  { sno: 9, name: "S Balaji\n(III Year B.Tech IT)", event: "HACKXTREME'26", level: "National", award: "Second Prize – Cash Award ₹15,000 & Internship Offer (Greensoft Solutions, Trichy)", title: "24-Hour National Level Hackathon" },
  { sno: 10, name: "V Mohanavel\n(III Year B.Tech IT)", event: "HACKXTREME'26", level: "National", award: "Second Prize – Cash Award ₹15,000 & Internship Offer (Greensoft Solutions, Trichy)", title: "24-Hour National Level Hackathon" },
  { sno: 11, name: "Sahul Hameed Dhameem M\n(III Year B.Tech IT)", event: "SUSEGAD SPRINT 2026 S01", level: "National", award: "First Prize – $500 Cash Prize & Trip to Goa", title: "Online Hackathon" },
  { sno: 12, name: "Mathankumar N\n(III Year B.Tech IT)", event: "SUSEGAD SPRINT 2026 S01", level: "National", award: "First Prize – $500 Cash Prize & Trip to Goa", title: "Online Hackathon" },
  { sno: 13, name: "Balaji S\n(III Year B.Tech IT)", event: "SUSEGAD SPRINT 2026 S01", level: "National", award: "First Prize – $500 Cash Prize & Trip to Goa", title: "Online Hackathon" },
  { sno: 14, name: "Nandha Kishore J\n(III Year B.Tech IT)", event: "SUSEGAD SPRINT 2026 S01", level: "National", award: "First Prize – $500 Cash Prize & Trip to Goa", title: "Online Hackathon" },
  { sno: 15, name: "Mohanvel V\n(III Year B.Tech IT)", event: "SUSEGAD SPRINT 2026 S01", level: "National", award: "First Prize – $500 Cash Prize & Trip to Goa", title: "Online Hackathon" }
];
export const itFacultyAwards = [];
