export const placementData2026 = {
  "placed": [
    {
      "sno": "1",
      "date": "11.06.2025",
      "company": "Infineon Technologies",
      "it_core": "CORE",
      "lpa": "13.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "2",
      "date": "18.02.2026",
      "company": "Nuvo AI Pvt. Ltd. (Meril Group)",
      "it_core": "IT",
      "lpa": "8.00 to 10.00",
      "cse": "",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "3",
      "date": "20.03.2026",
      "company": "TCS (Prime)",
      "it_core": "IT",
      "lpa": "9.09",
      "cse": "",
      "it": "",
      "csbs": "1",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "4",
      "date": "17.04.2026",
      "company": "Business Gateways International",
      "it_core": "IT",
      "lpa": "7.45",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "1",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "5",
      "date": "20.03.2026",
      "company": "TCS (Digital)",
      "it_core": "IT",
      "lpa": "7.09",
      "cse": "2",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "3"
    },
    {
      "sno": "6",
      "date": "23.09.2025 & 31.01.2026",
      "company": "Zoho Corporation",
      "it_core": "IT",
      "lpa": "7.00",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "0",
      "civil": "0",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "7",
      "date": "31.07.2025  01.08.2025",
      "company": "Kaar Technologies",
      "it_core": "IT",
      "lpa": "6.50",
      "cse": "4",
      "it": "1",
      "csbs": "0",
      "aids": "2",
      "ece": "0",
      "eee": "0",
      "mech": "1",
      "civil": "",
      "single": "8",
      "total": "8"
    },
    {
      "sno": "8",
      "date": "30.08.2025 & 26.03.2026",
      "company": "Logesys Solutions India Private Ltd.",
      "it_core": "IT",
      "lpa": "6.00",
      "cse": "0",
      "it": "1",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "1",
      "single": "",
      "total": ""
    },
    {
      "sno": "9",
      "date": "26.02.2026",
      "company": "Cyient",
      "it_core": "IT",
      "lpa": "6.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "10",
      "date": "01.09.2025 & 11.10.2025",
      "company": "AVA SOFTWARE Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "6.00",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "11",
      "date": "24.07.2025",
      "company": "SPI Sales and Marketing LLP (Sales Partners)",
      "it_core": "HR",
      "lpa": "6.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "12",
      "date": "05.09.2025",
      "company": "3Phase Engineering Solutions Pvt.Ltd.",
      "it_core": "CORE",
      "lpa": "5.10",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "8",
      "mech": "",
      "civil": "",
      "single": "7",
      "total": "8"
    },
    {
      "sno": "13",
      "date": "18.12.2025",
      "company": "Cloud Ambassador",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "0",
      "it": "0",
      "csbs": "1",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "14",
      "date": "26.02.2026",
      "company": "CTRLS",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "2",
      "mech": "0",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "15",
      "date": "25.03.2026 & 26.03.2026",
      "company": "Phoenix Cloud Technologies",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "1",
      "it": "0",
      "csbs": "",
      "aids": "0",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "16",
      "date": "21.10.2026",
      "company": "Indium Software (India) Limited",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "2",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "17",
      "date": "",
      "company": "Synopsys",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "18",
      "date": "19.02.2026",
      "company": "Autoliv",
      "it_core": "CORE",
      "lpa": "5.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "19",
      "date": "17.06.2025",
      "company": "Tranzyd Solutions Pvt.Ltd",
      "it_core": "IT",
      "lpa": "4.80",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "20",
      "date": "14.11.2025 & 15.11.2025",
      "company": "Cognizant (Japanese Hiring)",
      "it_core": "IT",
      "lpa": "4.76",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "21",
      "date": "16.07.2025",
      "company": "Adople AI Ventures",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "0",
      "it": "2",
      "csbs": "1",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "3"
    },
    {
      "sno": "22",
      "date": "26.08.2025",
      "company": "Brahmarsive India Private Limited",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "0",
      "csbs": "0",
      "aids": "1",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "23",
      "date": "15.10.2025",
      "company": "HCL Tech",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "16",
      "it": "3",
      "csbs": "2",
      "aids": "7",
      "ece": "5",
      "eee": "2",
      "mech": "",
      "civil": "",
      "single": "30",
      "total": "35"
    },
    {
      "sno": "24",
      "date": "09.12.2025",
      "company": "VirtualMaze Softsys Private Limited",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "2",
      "it": "0",
      "csbs": "3",
      "aids": "2",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "6",
      "total": "7"
    },
    {
      "sno": "25",
      "date": "25.04.2026",
      "company": "Winfo Solution",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "0",
      "it": "0",
      "csbs": "",
      "aids": "2",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "26",
      "date": "28.07.2025",
      "company": "Wspl Hosting Solution OPC Private Limited",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "27",
      "date": "16.08.2025",
      "company": "A Ciscr AI Pvt. Ltd. (Sekyurity )",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "28",
      "date": "06.10.2025",
      "company": "Protowiz",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "29",
      "date": "06.12.2025",
      "company": "GenSharp Solutions Pvt. Ltd",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "30",
      "date": "24.12.2025",
      "company": "Southindia Trading LLP",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "31",
      "date": "30.01.2026",
      "company": "Thistle Media Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "32",
      "date": "02.03.2026",
      "company": "Mulecraft India Private Limited",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "33",
      "date": "06.03.2026",
      "company": "Blackstraw Technologies",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "1",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "34",
      "date": "12.03.2026",
      "company": "Sanlayan Technologies",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "35",
      "date": "31.03.2026",
      "company": "Ausweg Info Controls Private Limited",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "1",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "36",
      "date": "06.03.2026",
      "company": "Sysnautix Technologies",
      "it_core": "CORE",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "2",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "37",
      "date": "27.04.2026",
      "company": "Vishay Precision",
      "it_core": "CORE",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "38",
      "date": "16.09.2025& 26.09.2025 08.10.2025",
      "company": "ITC Infotech",
      "it_core": "IT",
      "lpa": "4.25",
      "cse": "17",
      "it": "2",
      "csbs": "5",
      "aids": "6",
      "ece": "",
      "eee": "",
      "mech": "5",
      "civil": "",
      "single": "30",
      "total": "35"
    },
    {
      "sno": "39",
      "date": "02.02.2026",
      "company": "Ethara-AI",
      "it_core": "IT",
      "lpa": "4.20",
      "cse": "",
      "it": "1",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "40",
      "date": "06.12.2025 & 16.03.2026",
      "company": "Synergech",
      "it_core": "CORE",
      "lpa": "4.20",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "41",
      "date": "12.12.2025",
      "company": "Tessolve Semiconductor Pvt. Ltd.",
      "it_core": "CORE",
      "lpa": "4.13",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "2",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "42",
      "date": "14.11.2025 & 15.11.2025",
      "company": "Cognizant (Japanese Hiring)",
      "it_core": "IT",
      "lpa": "4.01",
      "cse": "",
      "it": "",
      "csbs": "1",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "43",
      "date": "30.07.2025",
      "company": "Hexaware Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "19",
      "it": "6",
      "csbs": "5",
      "aids": "4",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "25",
      "total": "34"
    },
    {
      "sno": "44",
      "date": "28.08.2026",
      "company": "L&T Edu Tech",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "1",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "45",
      "date": "02.09.2025",
      "company": "Jamocha Tech Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "2",
      "it": "2",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "46",
      "date": "22.09.2025",
      "company": "American Megatrends",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "4",
      "it": "1",
      "csbs": "1",
      "aids": "2",
      "ece": "1",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "10",
      "total": "10"
    },
    {
      "sno": "47",
      "date": "10.10.20235 & 04.03.2026",
      "company": "VVDN Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "8",
      "eee": "2",
      "mech": "",
      "civil": "",
      "single": "7",
      "total": "10"
    },
    {
      "sno": "48",
      "date": "13.11.2025 & 27.11.2025",
      "company": "Think Innov Solutions",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "3",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "3",
      "total": "4"
    },
    {
      "sno": "49",
      "date": "14.11.2025",
      "company": "Vinsinfo",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "4",
      "it": "0",
      "csbs": "2",
      "aids": "3",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "4",
      "total": "9"
    },
    {
      "sno": "50",
      "date": "02.01.2026",
      "company": "Expleo Solutions",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "10",
      "it": "4",
      "csbs": "5",
      "aids": "4",
      "ece": "6",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "29",
      "total": "30"
    },
    {
      "sno": "51",
      "date": "20.01.2026",
      "company": "Codingmart Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "3",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "52",
      "date": "30.01.2026",
      "company": "Arche Global",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "6",
      "it": "3",
      "csbs": "1",
      "aids": "3",
      "ece": "3",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "16",
      "total": "16"
    },
    {
      "sno": "53",
      "date": "10.02.2026",
      "company": "Waves Digital Media",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "5",
      "it": "0",
      "csbs": "4",
      "aids": "2",
      "ece": "",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "8",
      "total": "11"
    },
    {
      "sno": "54",
      "date": "11.02.2026",
      "company": "iMerit Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "31",
      "it": "8",
      "csbs": "7",
      "aids": "10",
      "ece": "2",
      "eee": "0",
      "mech": "",
      "civil": "0",
      "single": "53",
      "total": "58"
    },
    {
      "sno": "55",
      "date": "11.03.2026 & 12.03.2026",
      "company": "ZUCI Systems",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "2",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "56",
      "date": "17.03.2026",
      "company": "Whitestone Software solutions and Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "1",
      "csbs": "0",
      "aids": "1",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "57",
      "date": "26.03.2026",
      "company": "SRM Tech",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "4",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "2",
      "total": "4"
    },
    {
      "sno": "58",
      "date": "27.03.2026",
      "company": "Star Health (AI for Data Analyst)",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "15",
      "it": "10",
      "csbs": "9",
      "aids": "6",
      "ece": "2",
      "eee": "1",
      "mech": "1",
      "civil": "0",
      "single": "40",
      "total": "44"
    },
    {
      "sno": "59",
      "date": "07.04.2026",
      "company": "Shahgaron",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "1",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "60",
      "date": "11.04.2025",
      "company": "Sketch Brahma Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "61",
      "date": "12.09.2025",
      "company": "Granite River Labs Technology Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "2",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "62",
      "date": "19.09.2025",
      "company": "Qbic Catalyst Partners Pvt Ltd.",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "2",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "63",
      "date": "15.12.2025",
      "company": "Srinsoft Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "3",
      "civil": "0",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "64",
      "date": "05.01.2026",
      "company": "Thinkinfo Expert Solutions",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "65",
      "date": "01.03.2026",
      "company": "Pargavan Cyber Solution",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "66",
      "date": "07.10.2025",
      "company": "Visteon",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "0",
      "it": "1",
      "csbs": "0",
      "aids": "2",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "67",
      "date": "16.10.2025",
      "company": "ANTO GLOBAL INDIA PVT LTD",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "2",
      "eee": "0",
      "mech": "0",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "68",
      "date": "01.11.2025",
      "company": "Nucor Rebar Fabrication Detailing & Estimating Pvt. Ltd",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "4",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "69",
      "date": "28.02.2026",
      "company": "Quest Global",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "8",
      "civil": "",
      "single": "6",
      "total": "8"
    },
    {
      "sno": "70",
      "date": "11.03.2026 & 17.04.2026",
      "company": "Tafe Access Limited",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "6",
      "civil": "",
      "single": "4",
      "total": "6"
    },
    {
      "sno": "71",
      "date": "20.03.2026",
      "company": "L&T Technology Services (LTTS)",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "6",
      "civil": "",
      "single": "6",
      "total": "6"
    },
    {
      "sno": "72",
      "date": "28.11.2025",
      "company": "Stellantis AVTEC Powertrain India Pvt. Ltd",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "7",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "6",
      "total": "7"
    },
    {
      "sno": "73",
      "date": "08.12.2025",
      "company": "VB Ceramic Consultant (Best Sastra)",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "1",
      "mech": "0",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "74",
      "date": "19.12.2025",
      "company": "Caliber Interconnects",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "4",
      "mech": "",
      "civil": "",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "75",
      "date": "23.12.2025",
      "company": "L&T",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "2",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "76",
      "date": "23.12.2025 & 13.02.2026",
      "company": "Janatics",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "3",
      "civil": "",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "77",
      "date": "27.12.2025",
      "company": "Dynamic Beneficial Acort Marketing Private Limited",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "78",
      "date": "05.01.2026",
      "company": "Aruna HR Solutions",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "79",
      "date": "06.01.2026",
      "company": "Sansel Calibration Laboratories LLP",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "80",
      "date": "10.02.2026",
      "company": "ENNOVI Mobility Solutions",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "81",
      "date": "02.03.2026",
      "company": "Medex Technologies Private Limited",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "82",
      "date": "02.03.2026",
      "company": "Pricol",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "83",
      "date": "09.03.2026",
      "company": "ANCIT",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "2",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "84",
      "date": "17.03.2026",
      "company": "BMS Infra Solutions",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "85",
      "date": "25.03.2026",
      "company": "Sundaravijayam Automobile Services Private Limited (Intern)",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "1",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "86",
      "date": "27.03.2026",
      "company": "Roots",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "87",
      "date": "16.04.2026",
      "company": "NR Ventures Private Limited",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "88",
      "date": "06.05.2026",
      "company": "Titan Engineering & Automation Limited",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "89",
      "date": "20.03.2026",
      "company": "TCS (Ninja)",
      "it_core": "IT",
      "lpa": "3.60",
      "cse": "4",
      "it": "",
      "csbs": "1",
      "aids": "1",
      "ece": "1",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "5",
      "total": "7"
    },
    {
      "sno": "90",
      "date": "30.01.2026 & 25.02.2026",
      "company": "Data Patterns (India) Limited",
      "it_core": "CORE",
      "lpa": "3.60",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "91",
      "date": "16.04.2026",
      "company": "High-Technext Engineering & Telecom Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "3.50 to 4.75",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "14",
      "eee": "2",
      "mech": "",
      "civil": "",
      "single": "15",
      "total": "16"
    },
    {
      "sno": "92",
      "date": "29.11.2025",
      "company": "DWB Tech Solutions",
      "it_core": "IT",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "3",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "2",
      "total": "4"
    },
    {
      "sno": "93",
      "date": "29.05.2025",
      "company": "Kone Elevators",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "1",
      "ece": "0",
      "eee": "2",
      "mech": "5",
      "civil": "",
      "single": "3",
      "total": "8"
    },
    {
      "sno": "94",
      "date": "08.08.2025",
      "company": "Simpson & Co. Ltd.",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "2",
      "eee": "1",
      "mech": "11",
      "civil": "",
      "single": "7",
      "total": "14"
    },
    {
      "sno": "95",
      "date": "01.09.2025",
      "company": "Harita TechServ",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "17",
      "civil": "",
      "single": "9",
      "total": "17"
    },
    {
      "sno": "96",
      "date": "27.09.2025",
      "company": "Krayons interior Systems Pvt. Ltd.",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "5",
      "single": "1",
      "total": "5"
    },
    {
      "sno": "97",
      "date": "30.09.2025",
      "company": "Blackstone (Rewide) Group Technologies Pvt. Ltd.",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "2",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "98",
      "date": "05.12.2025",
      "company": "Exotic Innovation",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "9",
      "single": "2",
      "total": "9"
    },
    {
      "sno": "99",
      "date": "24.12.2025",
      "company": "The KCP Limited",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "3",
      "civil": "",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "100",
      "date": "29.12.2025",
      "company": "GK Power Expertise (ARRAA ENERGY PRIVATE LIMITED)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "6",
      "eee": "7",
      "mech": "",
      "civil": "",
      "single": "5",
      "total": "13"
    },
    {
      "sno": "101",
      "date": "19.02.2026",
      "company": "Webberax Solutions Pvt. Ltd.",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "2",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "1",
      "eee": "0",
      "mech": "0",
      "civil": "0",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "102",
      "date": "12.03.2026",
      "company": "NASH Inspired Engineering",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "28",
      "eee": "7",
      "mech": "23",
      "civil": "",
      "single": "27",
      "total": "58"
    },
    {
      "sno": "103",
      "date": "13.03.2026",
      "company": "VPG Sensor",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "41",
      "eee": "11",
      "mech": "0",
      "civil": "",
      "single": "19",
      "total": "52"
    },
    {
      "sno": "104",
      "date": "13.04.2026",
      "company": "Jost India Auto Component Pvt. Ltd",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "15",
      "civil": "",
      "single": "13",
      "total": "15"
    },
    {
      "sno": "105",
      "date": "12.12.2025",
      "company": "Unitech Plasto (Best Sastra)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "16",
      "eee": "5",
      "mech": "16",
      "civil": "",
      "single": "9",
      "total": "37"
    },
    {
      "sno": "106",
      "date": "12.12.2025",
      "company": "Tata Electronics (Best Sastra)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "1",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "2"
    },
    {
      "sno": "107",
      "date": "30.12.2025",
      "company": "Ferrigor Prestressed Concrete Contracting L.L.C S.O.C",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "4",
      "single": "4",
      "total": "4"
    },
    {
      "sno": "108",
      "date": "01.01.2026",
      "company": "KT Telematics (Best Sastra)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "2",
      "eee": "1",
      "mech": "0",
      "civil": "",
      "single": "3",
      "total": "3"
    },
    {
      "sno": "109",
      "date": "12.01.2026",
      "company": "TVS Upasana Lds (Best Sastra)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "0",
      "mech": "5",
      "civil": "",
      "single": "3",
      "total": "5"
    },
    {
      "sno": "110",
      "date": "13.01.2026",
      "company": "Genn Automation",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "5",
      "mech": "",
      "civil": "",
      "single": "5",
      "total": "5"
    },
    {
      "sno": "111",
      "date": "20.01.2026",
      "company": "Consolidate Construction Consortium Ltd (CCCL)",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "2",
      "single": "1",
      "total": "2"
    },
    {
      "sno": "112",
      "date": "02.03.2026",
      "company": "Rebar Design & Detailing Services",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "6",
      "single": "6",
      "total": "6"
    },
    {
      "sno": "113",
      "date": "21.03.2026",
      "company": "Pramoda Rebar Private Limited",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "2",
      "single": "2",
      "total": "2"
    },
    {
      "sno": "114",
      "date": "27.03.2026",
      "company": "DBA Private Limited",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "115",
      "date": "15.04.2026",
      "company": "Campus Connection",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "1",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "1",
      "total": "1"
    },
    {
      "sno": "116",
      "date": "19.05.2026",
      "company": "Tap Group of Companies",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "4",
      "mech": "14",
      "civil": "",
      "single": "15",
      "total": "18"
    },
    {
      "sno": "117",
      "date": "11.10.2025",
      "company": "Chip Test",
      "it_core": "IT",
      "lpa": "3.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "1",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "118",
      "date": "15.02.2026",
      "company": "MarqWon Dynamics Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "1",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "119",
      "date": "15.04.2026",
      "company": "SLS TTIC Pvt Ltd",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "1",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "120",
      "date": "24.10.2025",
      "company": "Hirotech India",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "121",
      "date": "31.10.2025",
      "company": "Rebar Design and Detail Private Limited",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "3",
      "single": "0",
      "total": "3"
    },
    {
      "sno": "122",
      "date": "10.12.2025",
      "company": "Skyray Power System",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "123",
      "date": "15.12.2025",
      "company": "Precise Rebar Estimating & Detailing",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "1",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "124",
      "date": "11.02.2026",
      "company": "Msteel Detailing Services",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "1",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "125",
      "date": "25.02.2026",
      "company": "Ashok Leyland",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "1"
    },
    {
      "sno": "126",
      "date": "27.02.2026",
      "company": "Megawins",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "1",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "1"
    }
  ],
  "opps": [
    {
      "sno": "1",
      "date": "30.06.2025",
      "company": "Mr.Cooper",
      "it_core": "IT",
      "lpa": "8.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "2",
      "date": "30.01.2026",
      "company": "MulticoreWare India (P) Ltd.",
      "it_core": "IT",
      "lpa": "7.20",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "3",
      "date": "28.01.2026",
      "company": "GE Vernova",
      "it_core": "CORE",
      "lpa": "7.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "4",
      "date": "09.12.2025",
      "company": "The Ramco Cements Limited",
      "it_core": "CORE",
      "lpa": "6.75",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "0",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "5",
      "date": "10.12.2025",
      "company": "Kovai.Co",
      "it_core": "IT",
      "lpa": "6.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "6",
      "date": "18.02.2026",
      "company": "embedUR Systems",
      "it_core": "IT",
      "lpa": "6.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "7",
      "date": "29.07.2025",
      "company": "Survey Sparrow",
      "it_core": "IT",
      "lpa": "5.50",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "8",
      "date": "19.03.2026",
      "company": "Emerson",
      "it_core": "CORE",
      "lpa": "5.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "0",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "9",
      "date": "29.04.2026",
      "company": "Schneider Electric",
      "it_core": "CORE",
      "lpa": "5.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "10",
      "date": "23.02.2026",
      "company": "Drive Stream",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "11",
      "date": "15.04.2026",
      "company": "LaunchED Global",
      "it_core": "IT",
      "lpa": "5.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "0",
      "civil": "0",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "12",
      "date": "12.02.2026",
      "company": "Bonfiglioli",
      "it_core": "CORE",
      "lpa": "5.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "13",
      "date": "07.01.2026 & 21.01.2026",
      "company": "Simplotel",
      "it_core": "IT",
      "lpa": "4.70",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "0",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "14",
      "date": "13.05.2026",
      "company": "HCLTech (Japanese Hiring)",
      "it_core": "IT",
      "lpa": "4.50 to 6.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "15",
      "date": "25.02.2026",
      "company": "IBM",
      "it_core": "IT",
      "lpa": "4.50",
      "cse": "",
      "it": "",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "16",
      "date": "30.01.2026",
      "company": "Truerize IQ Strategic Solutions Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "4.00 to 4.50",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "17",
      "date": "22.12.2025 & 27.12.2025",
      "company": "Thiran Technologies",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "18",
      "date": "05.03.2026",
      "company": "Worktual Innovations",
      "it_core": "IT",
      "lpa": "4.00",
      "cse": "0",
      "it": "",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "19",
      "date": "23.12.2025",
      "company": "Meltronics",
      "it_core": "CORE",
      "lpa": "4.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "20",
      "date": "30.03.2026",
      "company": "Jasmin InfoTech",
      "it_core": "IT",
      "lpa": "3.75",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "21",
      "date": "10.10.2025 & 11.10.2025",
      "company": "TCS Code Vita Season XIII",
      "it_core": "IT",
      "lpa": "3.60",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "22",
      "date": "20.02.2026",
      "company": "Sisco Energy Private Limited",
      "it_core": "CORE",
      "lpa": "3.60",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "23",
      "date": "09.03.2026",
      "company": "BGR Neo Ltd",
      "it_core": "CORE",
      "lpa": "3.60",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "24",
      "date": "16.03.2026",
      "company": "EWALL",
      "it_core": "IT",
      "lpa": "3.50",
      "cse": "",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "25",
      "date": "16.03.2026",
      "company": "MGS Technologies Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "3.50",
      "cse": "0",
      "it": "0",
      "csbs": "",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "26",
      "date": "13.04.2026",
      "company": "Teclever",
      "it_core": "IT",
      "lpa": "3.50",
      "cse": "0",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "27",
      "date": "07.11.2025",
      "company": "Harmony Environmental Systems Private Limited",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "28",
      "date": "17.04.2026",
      "company": "Upshot Engineering LLP",
      "it_core": "CORE",
      "lpa": "3.50",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "29",
      "date": "22.09.2025",
      "company": "SmartDV Technologies India Pvt.Ltd.",
      "it_core": "IT",
      "lpa": "3.39",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "30",
      "date": "17.04.2026",
      "company": "L-Cube Innovative Solutions Pvt. Ltd. (Glenwood Systems)",
      "it_core": "IT",
      "lpa": "3.00 to 4.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "31",
      "date": "30.12.2025",
      "company": "Vaken Technologies",
      "it_core": "IT",
      "lpa": "3.00",
      "cse": "0",
      "it": "0",
      "csbs": "0",
      "aids": "0",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "32",
      "date": "27.01.2026",
      "company": "iMatiz Technologies",
      "it_core": "IT",
      "lpa": "3.00",
      "cse": "0",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "33",
      "date": "29.04.2026",
      "company": "Atozerv India Pvt. Ltd.",
      "it_core": "IT",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "0",
      "eee": "",
      "mech": "",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "34",
      "date": "27.10.2025",
      "company": "Sobha Limited",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "",
      "civil": "0",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "35",
      "date": "13.04.2026",
      "company": "Esskay Design and Structures Pvt. Ltd.",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    },
    {
      "sno": "36",
      "date": "04.05.2026",
      "company": "Weg Industry",
      "it_core": "CORE",
      "lpa": "3.00",
      "cse": "",
      "it": "",
      "csbs": "",
      "aids": "",
      "ece": "",
      "eee": "0",
      "mech": "0",
      "civil": "",
      "single": "0",
      "total": "0"
    }
  ],
  "summary": [
    {
      "title": "Total No. of Students",
      "cse": "179",
      "it": "58",
      "csbs": "60",
      "aids": "59",
      "ece": "122",
      "eee": "61",
      "mech": "113",
      "civil": "28",
      "total": "680"
    },
    {
      "title": "Higher Studies",
      "cse": "21",
      "it": "0",
      "csbs": "7",
      "aids": "2",
      "ece": "15",
      "eee": "5",
      "mech": "12",
      "civil": "5",
      "total": "67"
    },
    {
      "title": "Entreprenur",
      "cse": "0",
      "it": "1",
      "csbs": "8",
      "aids": "0",
      "ece": "0",
      "eee": "0",
      "mech": "1",
      "civil": "0",
      "total": "10"
    },
    {
      "title": "Opted for Placement",
      "cse": "158",
      "it": "57",
      "csbs": "45",
      "aids": "57",
      "ece": "107",
      "eee": "56",
      "mech": "100",
      "civil": "23",
      "total": "603"
    },
    {
      "title": "Effective Placement (so far)",
      "cse": "147",
      "it": "53",
      "csbs": "43",
      "aids": "54",
      "ece": "103",
      "eee": "54",
      "mech": "96",
      "civil": "22",
      "total": "572"
    },
    {
      "title": "Dual Offers",
      "cse": "19",
      "it": "4",
      "csbs": "9",
      "aids": "11",
      "ece": "68",
      "eee": "28",
      "mech": "55",
      "civil": "17",
      "total": "783"
    },
    {
      "title": "Total Offers",
      "cse": "166",
      "it": "57",
      "csbs": "52",
      "aids": "65",
      "ece": "171",
      "eee": "82",
      "mech": "151",
      "civil": "39",
      "total": "1355"
    },
    {
      "title": "% of Placement",
      "cse": "93.04",
      "it": "92.98",
      "csbs": "95.56",
      "aids": "94.74",
      "ece": "96.26",
      "eee": "96.43",
      "mech": "96.00",
      "civil": "95.65",
      "total": "94.86"
    }
  ]
};