export const eceStudentAchievements = [
  { sno: 1, name: 'Manoj Kanna M', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 2, name: 'Harshini K', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 3, name: 'Jaisurya J J', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 4, name: 'Kesika S', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 5, name: 'Manishankar K', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 6, name: 'Elavarasi K', event: 'Smart India Hackathon 2025', level: 'National', award: 'Participation Certificate', title: 'Hardware to detect and prevent unauthorized use of electric fence' },
  { sno: 7, name: 'Sumetha A', event: 'Technical Event – VVDN Technologies; ICT Academy Youth Talk 2025', level: 'State; Regional', award: 'Participation Certificate; Regional Finale Certificate', title: 'PRODUCT360; Youth Talk 2025' },
  { sno: 8, name: 'Praveenkumar S', event: 'IBM Skill Build & IMIB; Tamilan Skills Ideathon', level: 'National; State', award: 'Participation Certificate; Participation Certificate', title: 'Mindscape Hackathon; Ideathon' },
  { sno: 9, name: 'Saran S', event: 'Tech and Innovation Fair 2026', level: 'National', award: 'Top 15 Finalist & Certificate of Appreciation', title: 'Agriculture Monitoring and Management System' },
  { sno: 10, name: 'Samuvel Praveen N', event: 'Tech and Innovation Fair 2026', level: 'National', award: 'Top 15 Finalist & Certificate of Appreciation', title: 'Agriculture Monitoring and Management System' },
  { sno: 11, name: 'Prasannavengat K', event: 'Tech and Innovation Fair 2026; IBM Skill Build & IMIB', level: 'National', award: 'Top 15 Finalist & Certificate of Appreciation; Participation Certificate', title: 'Agriculture Monitoring and Management System; Mindscape Hackathon' },
  { sno: 12, name: 'Srinithi G', event: 'The Next Hackathon 2025; 24-Hrs Non Stop Women Hackathon', level: 'National; Intra College', award: 'Participation Certificate; First Prize', title: 'Multispectral Image Based Crop Monitoring System; Multispectral Imaging Smart Drone for Orchard Management' },
  { sno: 13, name: 'Shanmugapriya S', event: 'The Next Hackathon 2025; Tamilan Skills Ideathon; 24-Hrs Non Stop Women Hackathon', level: 'National; State; Intra College', award: 'Participation Certificate; Participation Certificate; First Prize', title: 'Multispectral Image Based Crop Monitoring System; Ideathon; Multispectral Imaging Smart Drone for Orchard Management' },
  { sno: 14, name: 'Shahana Sri K S', event: 'The Next Hackathon 2025; 24-Hrs Non Stop Women Hackathon', level: 'National; Intra College', award: 'Participation Certificate; First Prize', title: 'Multispectral Image Based Crop Monitoring System; Multispectral Imaging Smart Drone for Orchard Management' },
  { sno: 15, name: 'Manigandan V', event: '24 Hours Hackathon (Hack IT on\'25)', level: 'State', award: 'Second Prize', title: 'Wireless Power Transmission for Electric Vehicle' },
  { sno: 16, name: 'Janani S', event: 'National Conference (ETABio-2025); National Conference', level: 'National', award: 'Second Place; Certificate of Appreciation', title: 'Future Scope of Paper Battery and a Normal Battery; Smart Agriculture using IoT: Enhancing Precision Farming and Crop Management' },
  { sno: 17, name: 'Dharani P V', event: 'Hackathon on Human-Wildlife Coexistence', level: 'National', award: 'Certificate of Recognition', title: 'Smart Electric Fence System for Wildlife and Human Safety' },
  { sno: 18, name: 'Aswika N', event: 'Hackathon on Human-Wildlife Coexistence', level: 'National', award: 'Certificate of Recognition', title: 'Smart Electric Fence System for Wildlife and Human Safety' },
  { sno: 19, name: 'Devashree S', event: 'SAEINDIA Southern Section Electric Four Wheeler Design Challenge 2025', level: 'National', award: 'Overall Third Prize', title: 'Electric Four Wheeler Design Challenge 2025' },
  { sno: 20, name: 'Harini S', event: 'SAEINDIA Southern Section Electric Four Wheeler Design Challenge 2025', level: 'National', award: 'Overall Third Prize', title: 'Electric Four Wheeler Design Challenge 2025' },
  { sno: 21, name: 'Bhaveshna S V', event: 'SAEINDIA Southern Section Electric Four Wheeler Design Challenge 2025', level: 'National', award: 'Overall Third Prize', title: 'Electric Four Wheeler Design Challenge 2025' },
  { sno: 22, name: 'Hari K S', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 23, name: 'Mohammed A Tharik A', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 24, name: 'Suhail M', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 25, name: 'Surendhar S', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 26, name: 'Prajithkumar R A', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 27, name: 'Praveenraj R', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 28, name: 'Rohith S M', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 29, name: 'Srinivasan K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 30, name: 'Prasanna S', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 31, name: 'Nikkesh G', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 32, name: 'Santhosh Kumar K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 33, name: 'Prem S K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 34, name: 'Vishal M', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 35, name: 'Sarvanan K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 36, name: 'Rajeshpandi K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 37, name: 'Santosh V S', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 38, name: 'Abhisheek S', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 39, name: 'Dharneshwar K', event: 'Indian E-Bike Championship Season 1', level: 'National', award: 'Participation Certificate', title: 'E-Bike' },
  { sno: 40, name: 'Gowtham A', event: 'Wild Frontiers\'25; ISTE Tamil Nadu Section', level: 'State', award: 'Second Prize; ISTE Best Student Award 2024', title: 'Product Demonstration' },
  { sno: 41, name: 'Jegan Athithiya S', event: 'National Level Competition on Embedded Systems 2025', level: 'National', award: 'Third Place', title: 'CHIPSYNC' },
  { sno: 42, name: 'Govarthanahari N', event: 'Internship through Infineon Hackathon; MSME Idea Hackathon 4.0', level: 'National', award: 'Internship Offer (₹40,000); ₹8.5 Lakh Funding', title: 'TonoLITE' },
  { sno: 43, name: 'Somasarathi S', event: 'MSME Idea Hackathon 4.0', level: 'National', award: '₹8.5 Lakh Funding', title: 'TonoLITE' },
  { sno: 44, name: 'Vaijayanthi R', event: '58th Engineers\' Day Celebrations; MSME Idea Hackathon 4.0', level: 'State; National', award: 'Dr. APJ Abdul Kalam Award; ₹8.5 Lakh Funding', title: 'TonoLITE' },
  { sno: 45, name: 'Tamilselvan C', event: 'MSME Idea Hackathon 4.0', level: 'National', award: '₹9 Lakh Funding', title: 'Landslide Monitoring and Warning System' },
  { sno: 46, name: 'Vignesh P', event: 'MSME Idea Hackathon 4.0', level: 'National', award: '₹9 Lakh Funding', title: 'Landslide Monitoring and Warning System' },
  { sno: 47, name: 'Shanmuga Prasanna D', event: 'MSME Idea Hackathon 4.0', level: 'National', award: '₹9 Lakh Funding', title: 'Landslide Monitoring and Warning System' },
  { sno: 48, name: 'Mahalakshmi P', event: 'MSME Idea Hackathon 4.0', level: 'National', award: '₹9 Lakh Funding', title: 'Landslide Monitoring and Warning System' },
  { sno: 49, name: 'Chandru P P', event: 'International Journal on Science and Technology', level: 'International', award: 'Published a Paper', title: 'Cluster-Aware Multimodal Transformer System' },
  { sno: 50, name: 'Krishnaraj G', event: 'Centre for Foreign Language', level: 'International', award: 'Japanese Certified (N4)', title: 'Cleared N4 Level (122/180)' },
  { sno: 51, name: 'Vijayvenkateshwara V', event: 'Centre for Foreign Language', level: 'International', award: 'Japanese Certified (NAT Q4)', title: 'Cleared NAT Q4 Level (110/180)' },
];
export const eceFacultyAchievements = [
  { sno: 1, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "21st EURECA International Engineering Research Conference, Taylor's University, Malaysia", level: "International", award: "Best Research Paper Award", title: "Best Research Paper Award" },
  { sno: 2, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "AICTE – ATAL FDP", level: "National", award: "₹6,00,000 Grant", title: "Harnessing Digital Healthcare Technologies: Bio-Markers, IoT, Data Analytics and AI in Precision Medicine" },
  { sno: 3, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "SERB Seminar", level: "National", award: "₹22,200 Grant", title: "NextGen SoC Architecture: Pioneering AI Integration in Signal Processing" },
  { sno: 4, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "A Leg Physiotherapy Apparatus and a Method for Operating the Same" },
  { sno: 5, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "Patent Published", level: "National", award: "Utility Patent Granted", title: "Tooth Mountable Hearing Aid" },
  { sno: 6, year: "2024-2025", name: "Dr. N. Santhiyakumari, Professor / ECE, Director – R&D", event: "Design Patent Granted", level: "National", award: "Utility Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 7, year: "2024-2025", name: "Dr. V. Saravanan, ASP & HoD / ECE", event: "21st EURECA International Engineering Research Conference, Taylor's University, Malaysia", level: "International", award: "Best Research Paper Award", title: "Best Research Paper Award" },
  { sno: 8, year: "2024-2025", name: "Dr. V. Saravanan, ASP & HoD / ECE", event: "AICTE – ATAL FDP", level: "National", award: "₹6,00,000 Grant", title: "Harnessing Digital Healthcare Technologies: Bio-Markers, IoT, Data Analytics and AI in Precision Medicine" },
  { sno: 9, year: "2024-2025", name: "Dr. V. Saravanan, ASP & HoD / ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "A Leg Physiotherapy Apparatus and a Method for Operating the Same" },
  { sno: 10, year: "2024-2025", name: "Dr. V. Saravanan, ASP & HoD / ECE", event: "Patent Published", level: "National", award: "Utility Patent Granted", title: "Tooth Mountable Hearing Aid" },
  { sno: 11, year: "2024-2025", name: "Dr. V. Saravanan, ASP & HoD / ECE", event: "Design Patent Granted", level: "National", award: "Utility Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 12, year: "2024-2025", name: "Mrs. M. Vasanthi, AP / ECE", event: "CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai", level: "National", award: "Best Faculty Award 2024", title: "Best Faculty Award 2024" },
  { sno: 13, year: "2024-2025", name: "Mrs. S. Sasidevi, AP / ECE", event: "CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai", level: "National", award: "Best Faculty Award 2024", title: "Best Faculty Award 2024" },
  { sno: 14, year: "2024-2025", name: "Mr. T. Praveenkumar, AP / ECE", event: "Tamil Nadu State Council for Science and Technology", level: "State", award: "₹7,500 Grant", title: "Login to Windows Computer using RFID Tag and Arduino" },
  { sno: 15, year: "2024-2025", name: "Mr. T. Praveenkumar, AP / ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "Machine Learning Assisted Healthcare Navigation Device" },
  { sno: 16, year: "2024-2025", name: "Mrs. S. Elarmathi, AP / ECE", event: "International Journal of Plasmonics", level: "International", award: "SCI Publication", title: "Advanced Plasmonic Resonance-Enhanced Biosensor for Comprehensive Real-Time Detection and Analysis of Deep Fake Content" },
  { sno: 17, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai", level: "National", award: "Best Faculty Award 2024", title: "Best Faculty Award 2024" },
  { sno: 18, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Plasmonics", level: "International", award: "SCI Publication", title: "Hybrid Plasmonic Biosensors with Deep Learning for Colorectal Cancer Detection" },
  { sno: 19, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Plasmonics", level: "International", award: "SCI Publication", title: "Advanced Plasmonic Resonance-Enhanced Biosensor for Comprehensive Real-Time Detection and Analysis of Deep Fake Content" },
  { sno: 20, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Journal of Computational Biology", level: "International", award: "SCI Publication", title: "Detection and Segmentation of Glioma Tumors Utilizing a UNet Convolutional Neural Network Approach with Non-Subsampled Shearlet Transform" },
  { sno: 21, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Microsystems Technologies", level: "International", award: "SCI Publication", title: "Novel Manufacturing Systems for Cancer Diagnosis Using Ultra-Sensitive Photonic Crystal Fiber Biosensor with Dual-Functionalized Aptamer-Nanocavity" },
  { sno: 22, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Journal of the Institution of Engineers (India): Series B", level: "International", award: "Scopus Publication", title: "A Strong Password Manager Using Multiple Encryption Techniques" },
  { sno: 23, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Technology and Health Care", level: "International", award: "SCI Publication", title: "An Automated Cervical Cancer Diagnosis Using Genetic Algorithm and CANFIS Approaches" },
  { sno: 24, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Plasmonics", level: "International", award: "SCI Publication", title: "Design of Surface Plasmon Resonance (SPR) Sensors for Highly Sensitive Biomolecular Detection in Cancer Diagnostics" },
  { sno: 25, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Networked and Distributed Computing", level: "International", award: "SCI Publication", title: "Modified Playfair for Text File Encryption and Meticulous Decryption with Arbitrary Fillers by Septenary Quadrate Pattern" },
  { sno: 26, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "Machine Learning Assisted Healthcare Navigation Device" },
  { sno: 27, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Design Patent Granted", level: "National", award: "Design Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 28, year: "2024-2025", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Applied Mathematics & Information Sciences", level: "International", award: "Scopus Publication", title: "Analysis of Computational Methods for Diagnosis of Cervical Cancer – A Review" },
  { sno: 29, year: "2024-2025", name: "Dr. M. Thangavel, Professor/ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "A Leg Physiotherapy Apparatus and a Method for Operating the Same" },
  { sno: 30, year: "2024-2025", name: "Dr. M. Thangavel, Director-CDT & Prof./ECE", event: "Patent Published", level: "National", award: "Utility Patent Published", title: "Machine Learning Assisted Healthcare Navigation Device" },
  { sno: 31, year: "2024-2025", name: "Dr. M. Thangavel, Director-CDT & Prof./ECE", event: "Patent Published", level: "National", award: "Utility Patent Published", title: "Tooth Mountable Hearing Aid" },
  { sno: 32, year: "2024-2025", name: "Dr. P. Shanmuga Sundaram, Director-Outreach & ASP/ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "A Leg Physiotherapy Apparatus and a Method for Operating the Same" },
  { sno: 33, year: "2024-2025", name: "Dr. P. Shanmuga Sundaram, Director-Outreach & ASP/ECE", event: "Patent Published", level: "National", award: "Utility Patent Published", title: "Tooth Mountable Hearing Aid" },
  { sno: 34, year: "2024-2025", name: "Mr.R. Shanmuga Sundaram, AP / ECE", event: "Patent Published", level: "National", award: "Design Patent Granted", title: "A Leg Physiotherapy Apparatus and a Method for Operating the Same" },
  { sno: 35, year: "2024-2025", name: "Mr.R. Shanmuga Sundaram, AP / ECE", event: "Patent Published", level: "National", award: "Utility Patent Granted", title: "Tooth Mountable Hearing Aid" },
  { sno: 36, year: "2024-2025", name: "Mr. S. Veerakumar, AP / ECE", event: "Design Patent Granted", level: "National", award: "Design Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 37, year: "2024-2025", name: "Mr. K. Rajesh, AP / ECE", event: "Design Patent Granted", level: "National", award: "Design Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 38, year: "2024-2025", name: "Mrs. T. Devika, AP / ECE", event: "Design Patent Granted", level: "National", award: "Design Patent Granted", title: "Cloud Based Healthcare Monitoring System using IoT" },
  { sno: 39, year: "2024-2025", name: "Mr. V. Vimalraj, AP / ECE", event: "Patent Published", level: "National", award: "Utility Patent Granted", title: "Machine Learning Assisted Healthcare Navigation Device" },
  { sno: 40, year: "2024-2025", name: "Mr. A. Silambarasan, AP / ECE", event: "Patent Published", level: "National", award: "Utility Patent Granted", title: "Machine Learning Assisted Healthcare Navigation Device" },
  { sno: 41, year: "2024-2025", name: "Mr. M. Duraisamy, AP / ECE", event: "NPTEL Course", level: "National", award: "Elite with Gold Certification", title: "Introduction to IoT" },
  { sno: 42, year: "2024-2025", name: "Mr. M. Duraisamy, AP / ECE", event: "NPTEL Course", level: "National", award: "Elite + Silver Certification", title: "Introduction to Industry 4.0 and Industrial Internet of Things" },
  { sno: 43, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "International Journal of Information Technology", level: "International", award: "Scopus", title: "Robust Adaptive Filtering through Dynamic Dual-Adaptation in α-Stable Conditions" },
  { sno: 44, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "Proceedings of the International Conference on Smart Cities, Springer Nature", level: "International", award: "Scopus", title: "Smart Waste Management System for Metropolitan Cities Leveraging IoT" },
  { sno: 45, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Enhancing Cardiovascular Disease Analysis in Healthcare Systems with Hybrid Random Forest and Neural Network Algorithm" },
  { sno: 46, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "Signal, Image and Video Processing", level: "International", award: "Scopus & SCIE", title: "Dynamic Step-Size Normalized LMS Algorithm for Alpha-Stable Impulsive Noise Control and Peak Tracking" },
  { sno: 47, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "International Journal of Plasmonics", level: "International", award: "Scopus & SCIE", title: "Hybrid Plasmonic Biosensors with Deep Learning for Colorectal Cancer Detection" },
  { sno: 48, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "Analog Integrated Circuits and Signal Processing", level: "International", award: "Scopus & SCIE", title: "Reducing Impulsive Noise in Active Noise Control Systems using FxLMS Algorithm Based on Soft Thresholding Techniques" },
  { sno: 49, year: "2025-2026", name: "Dr. N. Santhiyakumari, Director-R&D & Prof./ECE", event: "School of Engineering, Taylor's University", level: "International", award: "Scopus & ESCI", title: "Artificial Intelligence Based New Approaches for Impulsive Noise Reduction Techniques" },
  { sno: 50, year: "2025-2026", name: "Dr. M. Thangavel, Director-CDT & Prof./ECE", event: "Signal, Image and Video Processing, Springer London", level: "International", award: "Scopus & SCIE", title: "Dynamic Step-Size Normalized LMS Algorithm for Alpha-Stable Impulsive Noise Control and Peak Tracking" },
  { sno: 51, year: "2025-2026", name: "Dr. M. Thangavel, Director-CDT & Prof./ECE", event: "International Journal of Plasmonics", level: "International", award: "Scopus & SCIE", title: "Hybrid Plasmonic Biosensors with Deep Learning for Colorectal Cancer Detection" },
  { sno: 52, year: "2025-2026", name: "Dr. M. Thangavel, Director-CDT & Prof./ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Development of an Ion-Sensitive Field-Effect Transistor Device for High-Performance Diagnostic and Clinical Biomedical Applications" },
  { sno: 53, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "University Research Park & Tamil Nadu Industrial Development Corporation Ltd.", level: "State", award: "Proposal Sanctioned – ₹24.00 Lakhs (Co-Principal Investigator)", title: "Automated Tyre Wear and Damage Detection System" },
  { sno: 54, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "International Journal of Information Technology", level: "International", award: "Scopus", title: "Robust Adaptive Filtering through Dynamic Dual-Adaptation in α-Stable Conditions" },
  { sno: 55, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "Signal, Image and Video Processing", level: "International", award: "Scopus & SCIE", title: "Dynamic Step-Size Normalized LMS Algorithm for Alpha-Stable Impulsive Noise Control and Peak Tracking" },
  { sno: 56, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "Analog Integrated Circuits and Signal Processing", level: "International", award: "Scopus & SCIE", title: "Reducing Impulsive Noise in Active Noise Control Systems using FxLMS Algorithm Based on Soft Thresholding Techniques" },
  { sno: 57, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "School of Engineering, Taylor's University", level: "International", award: "Scopus & ESCI", title: "Artificial Intelligence Based New Approaches for Impulsive Noise Reduction Techniques" },
  { sno: 58, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "Journal of Engineering and Applied Science (Springer)", level: "International", award: "Scopus", title: "Active Impulsive Noise Control Using α-Score-Matched Robust Filtered-X Normalized Adaptation" },
  { sno: 59, year: "2025-2026", name: "Dr. V. Saravanan, HoD & ASP/ECE", event: "Proceedings of the International Conference on Smart Cities, Springer Nature", level: "International", award: "Scopus", title: "Smart Waste Management System for Metropolitan Cities Leveraging IoT" },
  { sno: 60, year: "2025-2026", name: "Dr. P. Shanmugasundaram, Director-Outreach & ASP/ECE", event: "International Journal of Information Technology", level: "International", award: "Scopus", title: "Robust Adaptive Filtering through Dynamic Dual-Adaptation in α-Stable Conditions" },
  { sno: 61, year: "2025-2026", name: "Dr. P. Shanmugasundaram, Director-Outreach & ASP/ECE", event: "Analog Integrated Circuits and Signal Processing", level: "International", award: "Scopus & SCIE", title: "Reducing Impulsive Noise in Active Noise Control Systems using FxLMS Algorithm Based on Soft Thresholding Techniques" },
  { sno: 62, year: "2025-2026", name: "Dr. P. Shanmugasundaram, Director-Outreach & ASP/ECE", event: "Journal of Engineering and Applied Science (Springer)", level: "International", award: "Scopus", title: "Active Impulsive Noise Control Using α-Score-Matched Robust Filtered-X Normalized Adaptation" },
  { sno: 63, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Medical Engineering and Informatics", level: "International", award: "Scopus", title: "Segmentation of the Human Spinal Cord Using U-Net Architecture" },
  { sno: 64, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Electronic Security and Digital Forensics", level: "International", award: "Scopus & ESCI", title: "Image Encryption Using Artificial Intelligence Algorithms for Secure Communication" },
  { sno: 65, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Springer", level: "International", award: "Scopus & SCIE", title: "Integration of Silver Nanostructures in Wireless Sensor Networks for Enhanced Biochemical Sensing" },
  { sno: 66, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Network (Bristol, England)", level: "International", award: "Scopus & SCIE", title: "Performance Analysis of Image Retrieval System Using Deep Learning Techniques" },
  { sno: 67, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Enhanced Circuit Board Analysis: Infrared Image Segmentation Utilizing Markov Random Field (MRF) and Level Set Techniques" },
  { sno: 68, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Development of an Ion-Sensitive Field-Effect Transistor Device for High-Performance Diagnostic and Clinical Biomedical Applications" },
  { sno: 69, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Scientific Reports", level: "International", award: "Scopus & SCIE", title: "Efficient Traffic Management with Adaptive SDN in Vehicular Networks" },
  { sno: 70, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Network: Computation in Neural Systems", level: "International", award: "Scopus & SCIE", title: "Classification of Meningioma Brain Images Using Convolutional Fuzzy C-Means Architecture" },
  { sno: 71, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Computers in Biology and Medicine", level: "International", award: "Scopus & SCIE", title: "Enhancing Healthcare Data Security Using RFE and CRHSM for Big Data" },
  { sno: 72, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Iran Journal of Computer Science", level: "International", award: "Scopus", title: "Advanced AI-Driven Emergency Response Systems for Enhanced Vehicle and Human Safety" },
  { sno: 73, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "International Journal of Plasmonics", level: "International", award: "Scopus & SCIE", title: "Hybrid Plasmonic Biosensors with Deep Learning for Colorectal Cancer Detection" },
  { sno: 74, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Journal of the Institution of Engineers (India): Series B", level: "International", award: "Scopus", title: "A Strong Password Manager Using Multiple Encryption Techniques" },
  { sno: 75, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Computers in Biology and Medicine (Pergamon)", level: "International", award: "Scopus & SCIE", title: "Enhancing Pancreatic Cancer Detection through RIDT-RLC" },
  { sno: 76, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Enhancing Cardiovascular Disease Analysis in Healthcare Systems with Hybrid Random Forest and Neural Network Algorithm" },
  { sno: 77, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Analog Integrated Circuits and Signal Processing", level: "International", award: "Scopus & SCIE", title: "Enhanced Adaptive Filtering in Audio Systems: NLMS with Cut-Set Retiming" },
  { sno: 78, year: "2025-2026", name: "Dr. S. Kumarganesh, Professor/ECE", event: "Systems and Soft Computing (Elsevier)", level: "International", award: "Scopus & SCIE", title: "Aggregated Approach for Interstitial Lung Diseases Classification Using Attention-Based CNN and RBF Neural Network" },
  { sno: 79, year: "2025-2026", name: "Mr. T. Praveenkumar, Assistant Prof./ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Enhanced Circuit Board Analysis: Infrared Image Segmentation Utilizing Markov Random Field (MRF) and Level Set Techniques" },
  { sno: 80, year: "2025-2026", name: "Mr. M. Chandraman, Assistant Prof./ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Enhancing Cardiovascular Disease Analysis in Healthcare Systems with Hybrid Random Forest and Neural Network Algorithm" },
  { sno: 81, year: "2025-2026", name: "Mr. M. Chandraman, Assistant Prof./ECE", event: "Niral Thirvizha 2.0", level: "Regional", award: "Cash Award (₹10,000)", title: "IoT-Based Public Toilets Monitoring System" },
  { sno: 82, year: "2025-2026", name: "Mr. M. Duraisamy, AP/ECE", event: "Engineering Reports", level: "International", award: "Scopus & ESCI", title: "Development of an Ion-Sensitive Field-Effect Transistor Device for High-Performance Diagnostic and Clinical Biomedical Applications" },
  { sno: 83, year: "2025-2026", name: "Mrs. R. Hemalatha, AP/ECE", event: "International Journal of Information Technology", level: "International", award: "Scopus", title: "Robust Adaptive Filtering through Dynamic Dual-Adaptation in α-Stable Conditions" },
  { sno: 84, year: "2025-2026", name: "Mrs. R. Hemalatha, AP/ECE", event: "Signal, Image and Video Processing", level: "International", award: "Scopus & SCIE", title: "Dynamic Step-Size Normalized LMS Algorithm for Alpha-Stable Impulsive Noise Control and Peak Tracking" },
  { sno: 85, year: "2025-2026", name: "Mrs. R. Hemalatha, AP/ECE", event: "NPTEL Course", level: "National", award: "Elite + Gold & Elite + Silver Certified", title: "Introduction to Internet of Things; Introduction to Industry 4.0 and Industrial IoT" },
  { sno: 86, year: "2025-2026", name: "Mr. K. Rajesh, AP/ECE", event: "Design Patent Granted", level: "National", award: "Patent Granted", title: "AI-Driven Environment Memory Drones Using Landmark-Vegetation Indexing" },
  { sno: 87, year: "2025-2026", name: "Mr. K. Rajesh, AP/ECE", event: "MSME Idea Hackathon 4.0", level: "National", award: "Cash Award (₹9 Lakh)", title: "Landslide Monitoring and Warning System" },
  { sno: 88, year: "2025-2026", name: "Mr. S. Premkumar, AP/ECE", event: "Niral Thirvizha 2.0", level: "Regional", award: "Cash Award (₹10,000)", title: "Inventory Management System for Medical Supply" },
  { sno: 89, year: "2025-2026", name: "Mr. A. Silambarasan, AP/ECE", event: "MSME Idea Hackathon 4.0", level: "National", award: "Cash Award (₹8.5 Lakh)", title: "TonoLITE" },
  { sno: 90, year: "2025-2026", name: "Mr. M. Dineshkumar, AP/ECE", event: "AICTE IDEA Lab Tech Fest, New Delhi", level: "National", award: "Shortlisted for Final Round", title: "AICTE-IDEA Lab Tech Fest Event" },
  { sno: 91, year: "2025-2026", name: "Mrs. T. Devika, AP/ECE", event: "Smart India Hackathon 2025 (Hardware Edition Grand Finale)", level: "National", award: "Mentor – Smart India Hackathon Grand Finale 2025", title: "A Hardware that Can Detect and Prevent Unauthorized Use of Electric Fence" }
];
export const eceStudentAwards = [];
export const eceFacultyAwards = [
  { sno: 1, name: 'Dr. S. Kumarganesh, Professor/ECE', event: 'CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai', level: 'National', award: 'Best Faculty Award', title: 'Best Faculty Award' },
  { sno: 2, name: 'Mrs. M. Vasanthi, AP / ECE', event: 'CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai', level: 'National', award: 'Best Faculty Award', title: 'Best Faculty Award' },
  { sno: 3, name: 'Mrs. S. Sasidevi, AP / ECE', event: 'CSI Mumbai Chapter, Dr. D. Y. Patil University, Navi Mumbai', level: 'National', award: 'Best Faculty Award', title: 'Best Faculty Award' },
  { sno: 4, name: 'Mrs. V. Vadivu', event: 'National Foundation for Innovative Scientific Research and Technology', level: 'National', award: 'International Women\'s Day award for Best Women Faculty.', title: 'International Women\'s Day award for Best Women Faculty.' }
];

export const eceFacultyNptel = [
  { sno: 1, name: 'Mr. M. Chandraman', designation: 'Assistant Professor', course: 'Research Methodology', certificate: 'Elite Certified' },
  { sno: 2, name: 'Mr. S Veerakumar', designation: 'Assistant Professor', course: 'Research Methodology', certificate: 'Elite Certified' },
  { sno: 3, name: 'Mrs. T Devika', designation: 'Assistant Professor', course: 'Microsensors and Nanosensors', certificate: 'Elite Certified' },
  { sno: 4, name: 'Mr. A.Arun', designation: 'Assistant Professor', course: 'Research Methodology', certificate: 'Elite Certified' },
  { sno: 5, name: 'Mr. V Vimalraj', designation: 'Assistant Professor', course: 'Microsensors and Nanosensors', certificate: 'Elite Certified' },
  { sno: 6, name: 'Mrs. M Vasanthi', designation: 'Assistant Professor', course: 'Microsensors and Nanosensors', certificate: 'Elite with Silver Certified' },
  { sno: 7, name: 'Mrs. R Hemalatha', designation: 'Assistant Professor', course: 'Introduction to Industry 4.0 and Industrial Internet of Things', certificate: 'Elite with Silver Certified' },
  { sno: 8, name: 'Mrs. S Elarmathi', designation: 'Assistant Professor', course: 'Microsensors and Nanosensors', certificate: 'Elite Certified' },
  { sno: 9, name: 'Mrs. S Sasidevi', designation: 'Assistant Professor', course: 'Microsensors and Nanosensors', certificate: 'Elite with Silver Certified' },
  { sno: 10, name: 'Mr. S.Sabarninathan', designation: 'Assistant Professor', course: 'Research Methodology', certificate: 'Elite Certified' },
  { sno: 11, name: 'Mr. S.Manoharan', designation: 'Assistant Professor', course: 'Qualitative Research Methods and Research Writing', certificate: 'Elite Certified' },
  { sno: 12, name: 'Mr. S.Veerakumar', designation: 'Assistant Professor', course: 'Crop Modeling and Simulation for Agricultural Production Management (CMSAM)', certificate: 'Elite+Silver' },
  { sno: 13, name: 'Mr. K.Rajesh', designation: 'Assistant Professor', course: 'Digital Electronic Circuits', certificate: 'Elite Certified' },
  { sno: 14, name: 'Mr. A.Arun', designation: 'Assistant Professor', course: 'Biomedical Signal Processing', certificate: 'Elite Certified' },
  { sno: 15, name: 'Mrs. R Hemalatha', designation: 'Assistant Professor', course: 'Digital Electronic Circuits', certificate: 'Elite Certified' },
  { sno: 16, name: 'Mrs. R Hemalatha', designation: 'Assistant Professor', course: 'Fundamentals of Semiconductor Devices', certificate: 'Elite Certified' }
];

export const eceStudentNptel = [
  { sno: 1, name: 'Abarna K', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 2, name: 'Abishek N', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 3, name: 'Brajeeth G', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 4, name: 'Dharshini P', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 5, name: 'Ganesh S', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 6, name: 'Hari K S', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 7, name: 'Janahan A S', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 8, name: 'Janani A M', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 9, name: 'Janani B', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 10, name: 'Lakshmi Shree R', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 11, name: 'Nandinipraba Y', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 12, name: 'Nikkesh G', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 13, name: 'Pravin kumar M', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 14, name: 'Ranjana S', course: 'Cyber Security and privacy', certificate: 'Elite' },
  { sno: 15, name: 'Reshma M', course: 'Practical Cyber Security for Cyber Security Practitioners', certificate: 'Elite+Gold' },
  { sno: 16, name: 'Santhosh V S', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 17, name: 'Srinithi G', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 18, name: 'Sruthi B', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 19, name: 'Sumetha A', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 20, name: 'Vikraman A', course: 'Practical Cyber Security for Cyber Security Practitioners', certificate: 'Elite+Silver' },
  { sno: 21, name: 'Abdul Rahman A', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 22, name: 'Asmathulla R', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 23, name: 'Aswin J', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 24, name: 'Deepak K', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 25, name: 'Dharanish V', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 26, name: 'Dharun D', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 27, name: 'Kowsalya C', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 28, name: 'Midhun B', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 29, name: 'Naveen M', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 30, name: 'Pradeesh A S', course: 'Cyber Security and Privacy', certificate: 'Elite' },
  { sno: 31, name: 'Ranganath C', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 32, name: 'Ranjithkumar R S', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 33, name: 'Rohith V', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 34, name: 'Shalini S', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 35, name: 'Sunmathi Manivelan', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 36, name: 'Suriyaa V M', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 37, name: 'Surya V', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 38, name: 'Tamilarasan K R', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 39, name: 'Vibheeshan N K', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 40, name: 'Vignesh K', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 41, name: 'Vinodhini M', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 42, name: 'Vishnu A', course: 'Microsensors and Nanosensors', certificate: 'Elite' },
  { sno: 43, name: 'Vishnu Vikas V', course: 'Microsensors and Nanosensors', certificate: 'Elite+Silver' },
  { sno: 44, regNo: '611223106001', name: 'Aarthiga J (611223106001)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 45, regNo: '611223106003', name: 'Abishek N (611223106003)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 46, regNo: '611223106007', name: 'Asar A (611223106007)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 47, regNo: '611223106011', name: 'Bhaveshna S V (611223106011)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 48, regNo: '611223106013', name: 'Brajeeth G (611223106013)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 49, regNo: '611223106015', name: 'Deepan S (611223106015)', course: 'Cloud computing', certificate: 'Elite' },
  { sno: 50, regNo: '611223106016', name: 'Deepeshraj K (611223106016)', course: 'Cloud Computing', certificate: 'Elite+Silver' },
  { sno: 51, regNo: '611223106017', name: 'Devashree S (611223106017)', course: 'Cloud computing', certificate: 'Elite' },
  { sno: 52, regNo: '611223106019', name: 'Dharaneesh K (611223106019)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 53, regNo: '611223106020', name: 'Dharaneesh S M (611223106020)', course: 'Sensor and Actuators', certificate: 'Elite+Silver' },
  { sno: 54, regNo: '611223106024', name: 'Dhatshinamoorthi N (611223106024)', course: 'Cloud computing', certificate: 'Elite' },
  { sno: 55, regNo: '611223106029', name: 'Durgaa M S (611223106029)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 56, regNo: '611223106031', name: 'Ganesh S (611223106031)', course: 'Cloud Computing', certificate: 'Elite+Silver' },
  { sno: 57, regNo: '611223106032', name: 'Gowtham K (611223106032)', course: 'Cloud Computing', certificate: 'Elite+Silver' },
  { sno: 58, regNo: '611223106033', name: 'Gowtam M (611223106033)', course: 'Cloud Computing', certificate: 'Elite+Silver' },
  { sno: 59, regNo: '611223106034', name: 'Hari K S (611223106034)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 60, regNo: '611223106036', name: 'Hariprakash B (611223106036)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 61, regNo: '611223106039', name: 'Jagan A K (611223106039)', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 62, regNo: '611223106042', name: 'Janani A M (611223106042)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 63, regNo: '611223106046', name: 'Kavin T (611223106046)', course: 'Cloud computing', certificate: 'Elite+Silver' },
  { sno: 64, regNo: '611223106047', name: 'Kavinraj S (611223106047)', course: 'Sensor and Actuators', certificate: 'Elite' },
  { sno: 65, regNo: '611223106049', name: 'Kesika S (611223106049)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 66, regNo: '611223106051', name: 'Krithika G M (611223106051)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 67, regNo: '611223106052', name: 'Lakshaya V (611223106052)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 68, regNo: '611223106053', name: 'Lakshmi Shree R (611223106053)', course: 'Sensor and actuators', certificate: 'Elite+Silver' },
  { sno: 69, regNo: '611223106059', name: 'Mohammed Akmad Tharik A (611223106059)', course: 'Smart Grid: Basics to Advanced Technologies', certificate: 'Elite' },
  { sno: 70, regNo: '611223106063', name: 'Nandinipraba Y (611223106063)', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 71, regNo: '611223106064', name: 'Nara Narayanan J (611223106064)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 72, regNo: '611223106065', name: 'Nikkesh G (611223106065)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 73, regNo: '611223106072', name: 'Prasanna S (611223106072)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 74, regNo: '611223106073', name: 'Prasannavengat K (611223106073)', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 75, regNo: '611223106086', name: 'Sachin S K (611223106086)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 76, regNo: '611223106087', name: 'Samuvel Praveen N (611223106087)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 77, regNo: '611223106089', name: 'Sandhiya R (611223106089)', course: 'Cloud computing', certificate: 'Elite' },
  { sno: 78, regNo: '611223106092', name: 'Santhosh V S (611223106092)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 79, regNo: '611223106093', name: 'Saran S (611223106093)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 80, regNo: '611223106096', name: 'Selvavignesh T (611223106096)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 81, regNo: '611223106099', name: 'Shanmugapriyaa S (611223106099)', course: 'Cloud computing', certificate: 'Elite+Silver' },
  { sno: 82, regNo: '611223106102', name: 'Sri MonikaMK (611223106102)', course: 'Cloud computing', certificate: 'Elite+Silver' },
  { sno: 83, regNo: '611223106104', name: 'Srinithi G (611223106104)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 84, regNo: '611223106110', name: 'Sumetha A (611223106110)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 85, regNo: '611223106301', name: 'Abisheak S (611223106301)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 86, regNo: '611223106117', name: 'Thenmozhi K (611223106117)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 87, regNo: '611223106121', name: 'Vikraman A (611223106121)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 88, regNo: '611223106301', name: 'Abisheak S (611223106301)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 89, regNo: '611223106305', name: 'Lokeshwaran R (611223106305)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 90, regNo: '611223106306', name: 'Manibharathi S (611223106306)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 91, regNo: '611223106308', name: 'Oviya Ranjani R F (611223106308)', course: 'Cloud Computing', certificate: 'Elite' },
  { sno: 92, regNo: '611224106010', name: 'Ahamed Rila N (611224106010)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 93, regNo: '611224106027', name: 'Deepanraj.D (611224106027)', course: 'Sensors and actuators', certificate: 'Elite' },
  { sno: 94, regNo: '611224106110', name: 'Nishanthi D (611224106110)', course: 'Cloud computing', certificate: 'Elite+Silver' },
  { sno: 95, regNo: '611224106128', name: 'Ranjithkumar R S (611224106128)', course: 'Sensors and Actuators', certificate: 'Elite+Silver' },
  { sno: 96, regNo: '611224106132', name: 'Rohith V (611224106132)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 97, regNo: '611224106136', name: 'Sanjaikumar S (611224106136)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 98, regNo: '611224106157', name: 'Tamilarasan K R (611224106157)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 99, regNo: '611224106165', name: 'Vedhayas S (611224106165)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 100, regNo: '611224106167', name: 'Vibheeshan N K (611224106167)', course: 'Sensors and Actuators', certificate: 'Elite' },
  { sno: 101, regNo: '611224106177', name: 'Yogesh K (611224106177)', course: 'Sensors and Actuators', certificate: 'Elite' }
];
